### ISSUE TITLE
ライブラリ画面を実装する

### ISSUE THREAD

**Issue by r-ca** [lacerta-doc/Lacerta#37]
# 概要

ファイルの一覧表示
# 詳細

・ファイルを一覧表示
・ドキュメントを管理（フォルダ管理）

# 関連Issue

# 影響箇所

**Comment by n-kent** [comment]
> # 概要
ライブラリ画面の基本的なUI
> # 詳細
　・フォルダ作成ボタン
　・ドキュメント追加ボタン
　・
> # 関連Issue
> # 影響箇所
　・

**Comment by n-kent** [comment]
> > # 概要
> 
> ライブラリ画面の基本的なUI
> 
> > # 詳細
> 
> 　・フォルダ作成ボタン 　・ドキュメント追加ボタン 　・
> 
> > # 関連Issue
> > # 影響箇所
> 
> 　・

**Comment by n-kent** [comment]
実行しても何らかのエラーによりアプリが落ちる

**Comment by n-kent** [comment]
エラーの原因を探ったら、おそらくgetAllDocumentMetasが関係している。

**Comment by n-kent** [comment]
Documentを使用していた部分をLacertaLibraryへ変更作業中

**Comment by n-kent** [comment]
コードの一部分がどうしても解決できずずっとエラーのままになっている
難しい、、、、

**Comment by n-kent** [comment]
なんとかエラーを解決することができた。ライブラリには、まだデータが出力されない状態になっている。
LacertaLibraryとLacertaLibraryImplのほうで、仮データが入ってる状態のため、出力されない。
おそらくこれで完全に実装することはできたと思う。

**Comment by n-kent** [comment]
いろいろ試しながらやっていたら、どうしてもエラーが起こりうまく表示されないため、もう一度見直しながら改善中

**Comment by r-ca** [comment]
巻き上げます！
